import type { ChemicalProduct } from '../types';

export interface IntelligenceLocation { latitude:number; longitude:number; name?:string; district?:string; }
export interface WeatherSnapshot { temperature:number; humidity:number; windSpeed:number; rainProbability:number; precipitation:number; dewPoint:number; uvIndex:number; et0:number; vpd:number; leafWetnessHours:number; fetchedAt:string; }
export interface SprayWindow { start:string; end:string; score:number; suitable:boolean; reasons:string[]; reasonsBn:string[]; }
export interface PesticideCandidate { product:ChemicalProduct; score:number; status:'preferred'|'acceptable'|'avoid'; reasons:string[]; reasonsBn:string[]; weatherFit:number; resistanceFit:number; }
export interface PesticideIntelligenceResult { weather:WeatherSnapshot; sprayWindows:SprayWindow[]; candidates:PesticideCandidate[]; diseasePressure:number; diseasePressureLabel:'low'|'moderate'|'high'; warnings:string[]; warningsBn:string[]; }

const API='https://api.open-meteo.com/v1/forecast';
const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:0;
const vpd=(t:number,d:number)=>{const es=.6108*Math.exp(17.27*t/(237.3+t));const ea=.6108*Math.exp(17.27*d/(237.3+d));return Math.max(0,es-ea)};
const cropMatch=(p:ChemicalProduct,c:string)=>!c.trim()||p.crops.some(x=>x.toLowerCase().includes(c.toLowerCase())||c.toLowerCase().includes(x.toLowerCase()));
const pestMatch=(p:ChemicalProduct,c:string)=>!c.trim()||p.pests.some(x=>x.toLowerCase().includes(c.toLowerCase())||c.toLowerCase().includes(x.toLowerCase()));
const sameMoa=(p:ChemicalProduct,last?:string)=>!!last&&!!p.moaCode&&(p.moaCode.toLowerCase().replace(/\\s/g,'')===last.toLowerCase().replace(/\\s/g,'')||p.moaCode.toLowerCase().split(/[\\/]/).some(x=>x&&last.toLowerCase().includes(x)));

function pressure(w:WeatherSnapshot){let s=0;if(w.humidity>=85)s+=35;else if(w.humidity>=75)s+=20;if(w.leafWetnessHours>=8)s+=30;else if(w.leafWetnessHours>=4)s+=18;if(w.temperature>=18&&w.temperature<=30)s+=20;if(w.rainProbability>=50)s+=15;return Math.min(100,s)}
function windows(w:WeatherSnapshot):SprayWindow[]{const suitable=w.windSpeed<=15&&w.rainProbability<35&&w.precipitation<.5;const score=Math.max(0,Math.min(100,100-Math.max(0,w.windSpeed-8)*4-Math.max(0,w.rainProbability-15)*.8-Math.max(0,w.temperature-32)*3));const reasons:string[]=[];const reasonsBn:string[]=[];if(w.windSpeed>15){reasons.push('Wind is too strong for a good spray window.');reasonsBn.push('বাতাসের গতি বেশি—স্প্রে করার উপযুক্ত সময় নয়।')}if(w.rainProbability>=35){reasons.push('Rain probability is elevated; allow a dry window.');reasonsBn.push('বৃষ্টির সম্ভাবনা বেশি—শুকনো সময় নিশ্চিত করুন।')}if(w.temperature>32){reasons.push('High temperature increases drift/evaporation risk.');reasonsBn.push('তাপমাত্রা বেশি—বাষ্পীভবন ও ড্রিফটের ঝুঁকি বাড়ে।')}if(!reasons.length){reasons.push('Weather is currently compatible with a cautious spray operation.');reasonsBn.push('বর্তমান আবহাওয়া সতর্কতার সাথে স্প্রে করার উপযোগী।')}const start=new Date(Date.now()+3600000).toISOString();const end=new Date(Date.now()+14400000).toISOString();return[{start,end,score,suitable,reasons,reasonsBn}]}

export async function fetchPesticideWeather(location:IntelligenceLocation):Promise<WeatherSnapshot>{const q=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),timezone:'auto',forecast_days:'3',current:'temperature_2m,relative_humidity_2m,wind_speed_10m,precipitation,dew_point_2m,uv_index',hourly:'relative_humidity_2m,precipitation',daily:'precipitation_probability_max,et0_fao_evapotranspiration'});const r=await fetch(API+'?'+q);if(!r.ok)throw new Error('Weather provider returned HTTP '+r.status);const d=await r.json();const c=d.current||{};const h=d.hourly||{};const day=d.daily||{};const hh:Array<number>=Array.isArray(h.relative_humidity_2m)?h.relative_humidity_2m:[];const rain:Array<number>=Array.isArray(h.precipitation)?h.precipitation:[];const leaf=hh.slice(0,24).filter((x,i)=>x>=90||n(rain[i])>0).length;const t=n(c.temperature_2m),dew=n(c.dew_point_2m);return{temperature:t,humidity:n(c.relative_humidity_2m),windSpeed:n(c.wind_speed_10m),rainProbability:n(Array.isArray(day.precipitation_probability_max)?day.precipitation_probability_max[0]:0),precipitation:n(c.precipitation),dewPoint:dew,uvIndex:n(c.uv_index),et0:n(Array.isArray(day.et0_fao_evapotranspiration)?day.et0_fao_evapotranspiration[0]:0),vpd:vpd(t,dew),leafWetnessHours:leaf,fetchedAt:new Date().toISOString()}}

export async function runPesticideIntelligence(a:{location:IntelligenceLocation;products:ChemicalProduct[];crop:string;pest?:string;lastMoa?:string}):Promise<PesticideIntelligenceResult>{const weather=await fetchPesticideWeather(a.location);const dp=pressure(weather);const candidates=a.products.filter(p=>cropMatch(p,a.crop)&&pestMatch(p,a.pest||'')).map(product=>{const wf=weather.windSpeed<=15&&weather.rainProbability<35?100:45;const repeated=sameMoa(product,a.lastMoa);const rf=repeated?0:product.resistanceRisk==='High'?45:85;let score=wf*.35+rf*.45+(product.phiDays==null?60:Math.max(0,100-product.phiDays))*.2;const reasons:string[]=[],reasonsBn:string[]=[];if(repeated){score-=60;reasons.push('Same MoA as the previous spray; rotate to a different group.');reasonsBn.push('আগের স্প্রের একই MoA; ভিন্ন গ্রুপে ঘূর্ণন করুন।')}else{reasons.push('Different MoA from the previous spray.');reasonsBn.push('আগের স্প্রের থেকে ভিন্ন MoA গ্রুপ।')}if(product.resistanceRisk==='High'){reasons.push('Higher resistance risk; follow the label and field need.');reasonsBn.push('প্রতিরোধ ঝুঁকি বেশি; লেবেল ও মাঠের প্রয়োজন অনুযায়ী ব্যবহার করুন।')}if(product.dosageRate){reasons.push('Label rate available: '+product.dosageRate);reasonsBn.push('লেবেলভিত্তিক মাত্রা: '+product.dosageRate)}const status=repeated||weather.windSpeed>20||weather.rainProbability>=70?'avoid':score>=72?'preferred':'acceptable';return{product,score:Math.round(Math.max(0,Math.min(100,score))),status,reasons,reasonsBn,weatherFit:wf,resistanceFit:rf}}).sort((x,y)=>y.score-x.score).slice(0,12);const warnings:string[]=[],warningsBn:string[]=[];if(weather.windSpeed>15){warnings.push('Do not spray in strong wind; reassess the next suitable window.');warningsBn.push('বাতাস বেশি হলে স্প্রে করবেন না; পরবর্তী উপযুক্ত সময় পুনর্মূল্যায়ন করুন।')}if(weather.rainProbability>=35){warnings.push('Rain is possible; follow the product label rainfast requirement.');warningsBn.push('বৃষ্টির সম্ভাবনা আছে; পণ্যের লেবেলের rainfast সময় মানুন।')}if(dp>=65){warnings.push('Weather is disease-favorable; monitor the crop before choosing a fungicide.');warningsBn.push('আবহাওয়া রোগের অনুকূল; ছত্রাকনাশক বাছাইয়ের আগে মাঠ পর্যবেক্ষণ করুন।')}return{weather,sprayWindows:windows(weather),candidates,diseasePressure:dp,diseasePressureLabel:dp>=65?'high':dp>=35?'moderate':'low',warnings,warningsBn}}
