# Python script to build complete insecticides dataset with official IRAC MoA mapping
import json
import re

# Comprehensive IRAC MoA Mapping based on official IRAC Classification up to 81st PTAC meeting
IRAC_MAP = {
    'Abamectin': {
        'code': 'IRAC 6',
        'group': 'Avermectins & Milbemycins (GluCl allosteric modulators)',
        'targetSite': 'Glutamate-gated chloride channels (GluCl)',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 7,
        'rei': 24,
        'water': 500
    },
    'Abamectin + acetamiprid': {
        'code': 'IRAC 6 + 4A',
        'group': 'Avermectin + Neonicotinoid Premix',
        'targetSite': 'GluCl allosteric modulator + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Abamectin + Beta Cypermethrin': {
        'code': 'IRAC 6 + 3A',
        'group': 'Avermectin + Pyrethroid Premix',
        'targetSite': 'GluCl modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Abamectin + Matrine': {
        'code': 'IRAC 6 + UN',
        'group': 'Avermectin + Botanical Alkaloid',
        'targetSite': 'GluCl modulator + Botanical unknown',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Abamectin + Propargite': {
        'code': 'IRAC 6 + 12C',
        'group': 'Avermectin + Organosulfite Miticide',
        'targetSite': 'GluCl modulator + ATP synthase inhibitor',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Abamectin + Imidacloprid': {
        'code': 'IRAC 6 + 4A',
        'group': 'Avermectin + Neonicotinoid Premix',
        'targetSite': 'GluCl modulator + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Abamectin + Chlorpyrifos': {
        'code': 'IRAC 6 + 1B',
        'group': 'Avermectin + Organophosphate Premix',
        'targetSite': 'GluCl modulator + Acetylcholinesterase (AChE) inhibitor',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Abamectin + Beta Cyfluthrin': {
        'code': 'IRAC 6 + 3A',
        'group': 'Avermectin + Pyrethroid Premix',
        'targetSite': 'GluCl modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Abamectin + Triazophos': {
        'code': 'IRAC 6 + 1B',
        'group': 'Avermectin + Organophosphate Premix',
        'targetSite': 'GluCl modulator + Acetylcholinesterase (AChE) inhibitor',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Abamectin + Indoxacarb': {
        'code': 'IRAC 6 + 22A',
        'group': 'Avermectin + Oxadiazine Premix',
        'targetSite': 'GluCl modulator + Voltage-dependent sodium channel blocker',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Beta Cyfluthrin + Imidacloprid': {
        'code': 'IRAC 3A + 4A',
        'group': 'Pyrethroid + Neonicotinoid Dual Action',
        'targetSite': 'Sodium channel + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Abamectin + Spirodiclofen': {
        'code': 'IRAC 6 + 23',
        'group': 'Avermectin + Tetronic Acid Miticide',
        'targetSite': 'GluCl modulator + Acetyl CoA carboxylase inhibitor',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Acephate': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 15,
        'rei': 24,
        'water': 500
    },
    'Acephate + Imidacloprid': {
        'code': 'IRAC 1B + 4A',
        'group': 'Organophosphate + Neonicotinoid Premix',
        'targetSite': 'AChE inhibitor + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 24,
        'water': 500
    },
    'Azocyclotin + Acetamiprid': {
        'code': 'IRAC 12B + 4A',
        'group': 'Organotin Miticide + Neonicotinoid Premix',
        'targetSite': 'ATP synthase inhibitor + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Acetamiprid': {
        'code': 'IRAC 4A',
        'group': 'Neonicotinoids (nAChR competitive modulators)',
        'targetSite': 'Nicotinic acetylcholine receptor (nAChR)',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 7,
        'rei': 12,
        'water': 400
    },
    'Alpha Cypermethrin': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Sodium channel modulators)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Amitraz': {
        'code': 'IRAC 19',
        'group': 'Formamidines (Octopamine receptor agonists)',
        'targetSite': 'Octopamine receptor agonist',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Azadirachtin': {
        'code': 'IRAC UN',
        'group': 'Botanical / Azadirachtin (Multi-site antifeedant)',
        'targetSite': 'Ecdysone disruptor and feeding deterrent',
        'risk': 'Low',
        'tox': 'U - Unlikely to Present Hazard',
        'whoColor': '#22c55e',
        'phi': 1,
        'rei': 4,
        'water': 500
    },
    'Beta Cypermethrin': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Sodium channel modulators)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Bifenthrin': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Sodium channel modulators)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Bifenthrin + Abamectin': {
        'code': 'IRAC 3A + 6',
        'group': 'Pyrethroid + Avermectin Premix',
        'targetSite': 'Sodium channel modulator + GluCl allosteric modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Bifenthrin + Zeta Cypermethrin': {
        'code': 'IRAC 3A + 3A',
        'group': 'Dual Pyrethroid Synergistic Complex',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Lufenuron + Bifenthrin': {
        'code': 'IRAC 15 + 3A',
        'group': 'Benzoylurea + Pyrethroid Premix',
        'targetSite': 'Chitin biosynthesis type 0 + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Abamectin + Hexythiazox': {
        'code': 'IRAC 6 + 10A',
        'group': 'Avermectin + Chitin Growth Inhibitor',
        'targetSite': 'GluCl modulator + Mite growth inhibitor (chitin)',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Buprofezin': {
        'code': 'IRAC 16',
        'group': 'Buprofezin (Chitin biosynthesis inhibitors type 1)',
        'targetSite': 'Chitin biosynthesis and moulting disruptor',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Buprofezin + Emamectin Benzoate': {
        'code': 'IRAC 16 + 6',
        'group': 'Chitin Biosynthesis Inhibitor + Avermectin',
        'targetSite': 'Chitin synthesis type 1 + GluCl modulator',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Isoprocarb + Buprofezin': {
        'code': 'IRAC 1A + 16',
        'group': 'Carbamate + Chitin Inhibitor Premix',
        'targetSite': 'AChE inhibitor + Chitin biosynthesis type 1',
        'risk': 'Medium to High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Buprofezin + Pymetrozine': {
        'code': 'IRAC 16 + 9B',
        'group': 'Chitin Inhibitor + Chordotonal Blocker Premix',
        'targetSite': 'Chitin synthesis type 1 + TRPV channel inhibitor',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Isoprocarb + Thiamethoxam': {
        'code': 'IRAC 1A + 4A',
        'group': 'Carbamate + Neonicotinoid Premix',
        'targetSite': 'AChE inhibitor + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Cadusafos': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitor nematicide)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'Ib - Highly Hazardous',
        'whoColor': '#ef4444',
        'phi': 60,
        'rei': 48,
        'water': 0
    },
    'Carbaryl': {
        'code': 'IRAC 1A',
        'group': 'Carbamates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Clothianidin': {
        'code': 'IRAC 4A',
        'group': 'Neonicotinoids (nAChR competitive modulators)',
        'targetSite': 'Nicotinic acetylcholine receptor (nAChR)',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Carbofuran': {
        'code': 'IRAC 1A',
        'group': 'Carbamates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'Ib - Highly Hazardous',
        'whoColor': '#ef4444',
        'phi': 30,
        'rei': 48,
        'water': 0
    },
    'Carbosulfan': {
        'code': 'IRAC 1A',
        'group': 'Carbamates (Pro-carbofuran AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Carbosulfan + Cypermethrin': {
        'code': 'IRAC 1A + 3A',
        'group': 'Carbamate + Pyrethroid Premix',
        'targetSite': 'AChE inhibitor + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Cartap': {
        'code': 'IRAC 14',
        'group': 'Nereistoxin analogues (nAChR channel blockers)',
        'targetSite': 'Nicotinic acetylcholine receptor channel block',
        'risk': 'Low to Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Acetamiprid + Cartap': {
        'code': 'IRAC 4A + 14',
        'group': 'Neonicotinoid + Nereistoxin Analogue Premix',
        'targetSite': 'nAChR agonist + nAChR ion channel blocker',
        'risk': 'Medium to High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Acetamiprid + Emamectin Benzoate': {
        'code': 'IRAC 4A + 6',
        'group': 'Neonicotinoid + Avermectin Premix',
        'targetSite': 'nAChR competitive modulator + GluCl allosteric modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Acetamiprid + Buprofezin': {
        'code': 'IRAC 4A + 16',
        'group': 'Neonicotinoid + Chitin Inhibitor Premix',
        'targetSite': 'nAChR agonist + Chitin synthesis type 1',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Acetamiprid + Imidacloprid': {
        'code': 'IRAC 4A + 4A',
        'group': 'Dual Neonicotinoid Complex',
        'targetSite': 'nAChR competitive modulators',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Cartap + Fipronil': {
        'code': 'IRAC 14 + 2B',
        'group': 'Nereistoxin Analogue + Phenylpyrazole Premix',
        'targetSite': 'nAChR channel block + GABA chloride channel blocker',
        'risk': 'Medium to High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Chlorfenapyr': {
        'code': 'IRAC 13',
        'group': 'Pyrroles (Uncouplers of oxidative phosphorylation)',
        'targetSite': 'Proton gradient uncoupling in mitochondria',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Chlorfenapyr + Emamectin Benzoate': {
        'code': 'IRAC 13 + 6',
        'group': 'Pyrrole + Avermectin Premix',
        'targetSite': 'Proton gradient disruptor + GluCl modulator',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Chlorfenapyr + Fipronil': {
        'code': 'IRAC 13 + 2B',
        'group': 'Pyrrole + Phenylpyrazole Premix',
        'targetSite': 'Proton gradient disruptor + GABA channel blocker',
        'risk': 'Medium to High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Chlorpyrifos': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Chlorpyrifos + Cypermethrin': {
        'code': 'IRAC 1B + 3A',
        'group': 'Organophosphate + Pyrethroid Premix (Nitro formulation)',
        'targetSite': 'AChE inhibitor + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Chlorpyrifos + Beta Cypermethrin': {
        'code': 'IRAC 1B + 3A',
        'group': 'Organophosphate + Pyrethroid Premix',
        'targetSite': 'AChE inhibitor + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Pymetrozine + Dinotefuran': {
        'code': 'IRAC 9B + 4A',
        'group': 'Chordotonal TRPV Modulator + Neonicotinoid',
        'targetSite': 'Chordotonal TRPV blocker + nAChR competitive modulator',
        'risk': 'Medium to High',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Chlorpyrifos + Pymetrozine': {
        'code': 'IRAC 1B + 9B',
        'group': 'Organophosphate + Chordotonal Organ Modulator',
        'targetSite': 'AChE inhibitor + TRPV channel blocker',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Cypermethrin': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Sodium channel modulators)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Cypermethrin + Dimethoate': {
        'code': 'IRAC 3A + 1B',
        'group': 'Pyrethroid + Organophosphate Premix',
        'targetSite': 'Sodium channel modulator + AChE inhibitor',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Deltamethrin': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Sodium channel modulators)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 7,
        'rei': 24,
        'water': 500
    },
    'Deltamethrin + Triazophos': {
        'code': 'IRAC 3A + 1B',
        'group': 'Pyrethroid + Organophosphate Premix',
        'targetSite': 'Sodium channel modulator + AChE inhibitor',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Diazinon': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Dimethoate': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (Systemic AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Dinotefuran': {
        'code': 'IRAC 4A',
        'group': 'Neonicotinoids (Third generation furanicotinyl)',
        'targetSite': 'Nicotinic acetylcholine receptor (nAChR)',
        'risk': 'High',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Dinotefuran + Fipronil': {
        'code': 'IRAC 4A + 2B',
        'group': 'Neonicotinoid + Phenylpyrazole Dual Action',
        'targetSite': 'nAChR competitive modulator + GABA channel blocker',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Diafenthiuron': {
        'code': 'IRAC 12A',
        'group': 'Diafenthiuron (Mitochondrial ATP synthase inhibitors)',
        'targetSite': 'Inhibitor of mitochondrial ATP synthase',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Etoxazole': {
        'code': 'IRAC 10B',
        'group': 'Etoxazole (Mite growth inhibitors)',
        'targetSite': 'Inhibitor of chitin biosynthesis in mites',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Emamectin Benzoate': {
        'code': 'IRAC 6',
        'group': 'Avermectins (GluCl allosteric modulators)',
        'targetSite': 'Glutamate-gated chloride channels (GluCl)',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Hexaflumuron + Emamectin Benzoate': {
        'code': 'IRAC 15 + 6',
        'group': 'Benzoylurea + Avermectin Premix',
        'targetSite': 'Chitin synthesis type 0 + GluCl allosteric modulator',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Abamectin + Emamectin Benzoate': {
        'code': 'IRAC 6 + 6',
        'group': 'Avermectin Synergistic Complex',
        'targetSite': 'Glutamate-gated chloride channels (GluCl)',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 7,
        'rei': 24,
        'water': 500
    },
    'Emamectin Benzoate + Beta Cypermethrin': {
        'code': 'IRAC 6 + 3A',
        'group': 'Avermectin + Pyrethroid Premix',
        'targetSite': 'GluCl modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Emamectin Benzoate + Chlorpyrifos': {
        'code': 'IRAC 6 + 1B',
        'group': 'Avermectin + Organophosphate Premix',
        'targetSite': 'GluCl modulator + Acetylcholinesterase inhibitor',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Tolfenpyrad + Emamectin Benzoate': {
        'code': 'IRAC 21A + 6',
        'group': 'METI Acaricide + Avermectin Premix',
        'targetSite': 'Mitochondrial complex I + GluCl channel modulator',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Emamectin Benzoate + Cartap': {
        'code': 'IRAC 6 + 14',
        'group': 'Avermectin + Nereistoxin Analogue Premix',
        'targetSite': 'GluCl modulator + nAChR channel blocker',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Indoxacarb + Emamectin Benzoate': {
        'code': 'IRAC 22A + 6',
        'group': 'Oxadiazine + Avermectin Premix',
        'targetSite': 'Voltage-dependent sodium channel + GluCl modulator',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Emamectin Benzoate + Lambda Cyhalothrin': {
        'code': 'IRAC 6 + 3A',
        'group': 'Avermectin + Pyrethroid Premix',
        'targetSite': 'GluCl modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Esfenvalerate': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Resolved chiral isomer)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 7,
        'rei': 24,
        'water': 500
    },
    'Ethion + Cypermethrin': {
        'code': 'IRAC 1B + 3A',
        'group': 'Organophosphate + Pyrethroid Premix',
        'targetSite': 'AChE inhibitor + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Ethion + Thiamethoxam': {
        'code': 'IRAC 1B + 4A',
        'group': 'Organophosphate + Neonicotinoid Premix',
        'targetSite': 'AChE inhibitor + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Fenazaquin': {
        'code': 'IRAC 21A',
        'group': 'METI Acaricides (Mitochondrial complex I inhibitors)',
        'targetSite': 'Mitochondrial electron transport complex I',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fenbutatin Oxide': {
        'code': 'IRAC 12B',
        'group': 'Organotin Miticides (ATP synthase inhibitors)',
        'targetSite': 'Inhibition of mitochondrial ATP synthase',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fenitrothion': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fenthion': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Fenvalerate': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Sodium channel modulators)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fipronil': {
        'code': 'IRAC 2B',
        'group': 'Phenylpyrazoles (GABA-gated chloride channel blockers)',
        'targetSite': 'GABA-gated chloride channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fipronil + Lambda Cyhalothrin': {
        'code': 'IRAC 2B + 3A',
        'group': 'Phenylpyrazole + Pyrethroid Premix',
        'targetSite': 'GABA channel blocker + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fipronil + Emamectin Benzoate': {
        'code': 'IRAC 2B + 6',
        'group': 'Phenylpyrazole + Avermectin Premix',
        'targetSite': 'GABA channel blocker + GluCl modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fipronil + Thiamethoxam': {
        'code': 'IRAC 2B + 4A',
        'group': 'Phenylpyrazole + Neonicotinoid Dual Action',
        'targetSite': 'GABA channel blocker + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fipronil + Phoxim': {
        'code': 'IRAC 2B + 1B',
        'group': 'Phenylpyrazole + Organophosphate Premix',
        'targetSite': 'GABA channel blocker + AChE inhibitor',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Fipronil + Sulfoxaflor': {
        'code': 'IRAC 2B + 4C',
        'group': 'Phenylpyrazole + Sulfoximine Premix',
        'targetSite': 'GABA channel blocker + nAChR allosteric/competitive',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Fipronil + Acetamiprid': {
        'code': 'IRAC 2B + 4A',
        'group': 'Phenylpyrazole + Neonicotinoid Premix',
        'targetSite': 'GABA channel blocker + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Flubendiamide': {
        'code': 'IRAC 28',
        'group': 'Diamides (Ryanodine receptor modulators)',
        'targetSite': 'Ryanodine receptor (RyR) in insect muscle cells',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Gamma Cyhalothrin': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Resolved pure isomer)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Imidacloprid': {
        'code': 'IRAC 4A',
        'group': 'Neonicotinoids (nAChR competitive modulators)',
        'targetSite': 'Nicotinic acetylcholine receptor (nAChR)',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 12,
        'water': 400
    },
    'Imidacloprid + Lambda Cyhalothrin': {
        'code': 'IRAC 4A + 3A',
        'group': 'Neonicotinoid + Pyrethroid Premix',
        'targetSite': 'nAChR competitive modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Imidacloprid + Monomehypo': {
        'code': 'IRAC 4A + 14',
        'group': 'Neonicotinoid + Nereistoxin Analogue Premix',
        'targetSite': 'nAChR agonist + nAChR ion channel blocker',
        'risk': 'Medium to High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Imidacloprid + Cypermethrin': {
        'code': 'IRAC 4A + 3A',
        'group': 'Neonicotinoid + Pyrethroid Premix',
        'targetSite': 'nAChR competitive modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Imidacloprid + Ethiprole': {
        'code': 'IRAC 4A + 2B',
        'group': 'Neonicotinoid + Phenylpyrazole Dual Action',
        'targetSite': 'nAChR agonist + GABA chloride channel blocker',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Imidacloprid + Fipronil': {
        'code': 'IRAC 4A + 2B',
        'group': 'Neonicotinoid + Phenylpyrazole Dual Action',
        'targetSite': 'nAChR agonist + GABA chloride channel blocker',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Imidacloprid + Chlorpyrifos': {
        'code': 'IRAC 4A + 1B',
        'group': 'Neonicotinoid + Organophosphate Premix',
        'targetSite': 'nAChR competitive modulator + AChE inhibitor',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Indoxacarb': {
        'code': 'IRAC 22A',
        'group': 'Oxadiazines (Voltage-dependent sodium channel blockers)',
        'targetSite': 'Voltage-dependent sodium channels (nerve blocker)',
        'risk': 'Low to Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Indoxacarb + Acetamiprid': {
        'code': 'IRAC 22A + 4A',
        'group': 'Oxadiazine + Neonicotinoid Premix',
        'targetSite': 'Voltage-dependent sodium channel + nAChR agonist',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Isoprocarb (MIPC)': {
        'code': 'IRAC 1A',
        'group': 'Carbamates (Rapid knockdown hopper specialists)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Lambda Cyhalothrin': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Sodium channel modulators)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Lufenuron': {
        'code': 'IRAC 15',
        'group': 'Benzoylureas (Chitin biosynthesis inhibitors type 0)',
        'targetSite': 'Inhibition of chitin biosynthesis (type 0)',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Lufenuron + Emamectin Benzoate': {
        'code': 'IRAC 15 + 6',
        'group': 'Chitin Biosynthesis Inhibitor + Avermectin',
        'targetSite': 'Chitin synthesis type 0 + GluCl modulator',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Malathion': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 24,
        'water': 500
    },
    'Monomehypo': {
        'code': 'IRAC 14',
        'group': 'Nereistoxin analogues (nAChR channel blockers)',
        'targetSite': 'Nicotinic acetylcholine receptor channel block',
        'risk': 'Low to Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Nitenpyram': {
        'code': 'IRAC 4A',
        'group': 'Neonicotinoids (nAChR competitive modulators)',
        'targetSite': 'Nicotinic acetylcholine receptor (nAChR)',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 7,
        'rei': 12,
        'water': 400
    },
    'Nitenpyram + Pymetrozine': {
        'code': 'IRAC 4A + 9B',
        'group': 'Neonicotinoid + Chordotonal Blocker Premix',
        'targetSite': 'nAChR agonist + TRPV channel blocker',
        'risk': 'Medium to High',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Nitenpyram + Diafenthiuron': {
        'code': 'IRAC 4A + 12A',
        'group': 'Neonicotinoid + ATP Synthase Inhibitor Premix',
        'targetSite': 'nAChR competitive modulator + Mitochondrial ATP synthase',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Osfencarb (BPMC)': {
        'code': 'IRAC 1A',
        'group': 'Carbamates (Fenobucarb / BPMC)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Phenthoate': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Phosmet': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (Phthalimide AChE inhibitor)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Phosphorous Acid': {
        'code': 'FRAC P07',
        'group': 'Host Plant Defense Inducers (Phosphonates)',
        'targetSite': 'Induction of plant systemic acquired resistance',
        'risk': 'Low',
        'tox': 'U - Unlikely to Present Hazard',
        'whoColor': '#22c55e',
        'phi': 1,
        'rei': 4,
        'water': 500
    },
    'Profenofos': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Profenofos + Cypermethrin': {
        'code': 'IRAC 1B + 3A',
        'group': 'Organophosphate + Pyrethroid Premix (Shobicron formulation)',
        'targetSite': 'AChE inhibitor + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Profenofos + Lambda Cyhalothrin': {
        'code': 'IRAC 1B + 3A',
        'group': 'Organophosphate + Pyrethroid Premix',
        'targetSite': 'AChE inhibitor + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Profenofos + Lufenuron': {
        'code': 'IRAC 1B + 15',
        'group': 'Organophosphate + Benzoylurea Premix',
        'targetSite': 'AChE inhibitor + Chitin biosynthesis type 0',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Pymetrozine': {
        'code': 'IRAC 9B',
        'group': 'Pyridine azomethines (Chordotonal TRPV modulators)',
        'targetSite': 'Selective feeding inhibitor for aphids & hoppers',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Pymetrozine + Imidacloprid': {
        'code': 'IRAC 9B + 4A',
        'group': 'Chordotonal TRPV Blocker + Neonicotinoid',
        'targetSite': 'Feeding blocker + nAChR competitive modulator',
        'risk': 'Medium to High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Pymetrozine + Thiamethoxam': {
        'code': 'IRAC 9B + 4A',
        'group': 'Chordotonal TRPV Blocker + Neonicotinoid',
        'targetSite': 'Feeding blocker + nAChR competitive modulator',
        'risk': 'Medium to High',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Pyridaben': {
        'code': 'IRAC 21A',
        'group': 'METI Acaricides (Mitochondrial complex I inhibitors)',
        'targetSite': 'Mitochondrial electron transport complex I',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Pyriproxyfen': {
        'code': 'IRAC 7C',
        'group': 'Pyriproxyfen (Juvenile hormone mimics)',
        'targetSite': 'Juvenile hormone receptor agonist',
        'risk': 'Low to Medium',
        'tox': 'U - Unlikely to Present Hazard',
        'whoColor': '#22c55e',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Pyriproxyfen + Bifenthrin': {
        'code': 'IRAC 7C + 3A',
        'group': 'Juvenile Hormone Mimic + Pyrethroid Premix',
        'targetSite': 'JH mimic + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Quinalphos': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Quinalphos + Cypermethrin': {
        'code': 'IRAC 1B + 3A',
        'group': 'Organophosphate + Pyrethroid Premix',
        'targetSite': 'AChE inhibitor + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Spinosad': {
        'code': 'IRAC 5',
        'group': 'Spinosyns (nAChR allosteric modulators - Site I)',
        'targetSite': 'Nicotinic acetylcholine receptor allosteric Site I',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 3,
        'rei': 4,
        'water': 500
    },
    'Spirotetramat': {
        'code': 'IRAC 23',
        'group': 'Tetramic acid derivatives (Lipid biosynthesis inhibitors)',
        'targetSite': 'Acetyl CoA carboxylase (two-way systemic transport)',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Spiromesifen': {
        'code': 'IRAC 23',
        'group': 'Tetronic acid derivatives (Lipid biosynthesis inhibitors)',
        'targetSite': 'Acetyl CoA carboxylase (lipid synthesis inhibitor)',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Thiamethoxam + Lambda Cyhalothrin': {
        'code': 'IRAC 4A + 3A',
        'group': 'Neonicotinoid + Pyrethroid Premix',
        'targetSite': 'nAChR competitive modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Thiacloprid': {
        'code': 'IRAC 4A',
        'group': 'Neonicotinoids (Chloronicotinyl class)',
        'targetSite': 'Nicotinic acetylcholine receptor (nAChR)',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Thiacloprid + Beta Cyfluthrin': {
        'code': 'IRAC 4A + 3A',
        'group': 'Neonicotinoid + Pyrethroid Premix',
        'targetSite': 'nAChR competitive modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Thiamethoxam': {
        'code': 'IRAC 4A',
        'group': 'Neonicotinoids (Second generation thianicotinyl)',
        'targetSite': 'Nicotinic acetylcholine receptor (nAChR)',
        'risk': 'High',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Thiamethoxam + Chlorantraniliprole': {
        'code': 'IRAC 4A + 28',
        'group': 'Neonicotinoid + Diamide Premix Dual Action',
        'targetSite': 'nAChR agonist + Ryanodine receptor activator',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Thiamethoxam + Imidacloprid': {
        'code': 'IRAC 4A + 4A',
        'group': 'Dual Neonicotinoid Complex',
        'targetSite': 'nAChR competitive modulators',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Emamectin Benzoate + Imidacloprid': {
        'code': 'IRAC 6 + 4A',
        'group': 'Avermectin + Neonicotinoid Premix',
        'targetSite': 'GluCl modulator + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Chlorantraniliprole': {
        'code': 'IRAC 28',
        'group': 'Diamides (Ryanodine receptor modulators)',
        'targetSite': 'Ryanodine receptor (RyR) in insect muscle cells',
        'risk': 'Low to Medium',
        'tox': 'U - Unlikely to Present Hazard',
        'whoColor': '#22c55e',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Thiodicarb': {
        'code': 'IRAC 1A',
        'group': 'Carbamates (Oxime carbamate AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Thiamethoxam + Emamectin Benzoate': {
        'code': 'IRAC 4A + 6',
        'group': 'Neonicotinoid + Avermectin Premix (Dual sucking & chewing)',
        'targetSite': 'nAChR competitive modulator + GluCl channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Thiamethoxam + Fipronil': {
        'code': 'IRAC 4A + 2B',
        'group': 'Neonicotinoid + Phenylpyrazole Dual Action',
        'targetSite': 'nAChR competitive modulator + GABA channel blocker',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Triazophos': {
        'code': 'IRAC 1B',
        'group': 'Organophosphates (AChE inhibitors)',
        'targetSite': 'Acetylcholinesterase (AChE) inhibition',
        'risk': 'High',
        'tox': 'Ib - Highly Hazardous',
        'whoColor': '#ef4444',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Zeta Cypermethrin': {
        'code': 'IRAC 3A',
        'group': 'Pyrethroids (Resolved active isomers)',
        'targetSite': 'Voltage-gated sodium channels',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Cyromazine': {
        'code': 'IRAC 17',
        'group': 'Cyromazine (Moulting disruptors, Dipteran)',
        'targetSite': 'Dipteran larval moulting and pupation disruption',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Cyromazin + Thiosultap Monosodium': {
        'code': 'IRAC 17 + 14',
        'group': 'Moulting Disruptor + Nereistoxin Analogue Premix',
        'targetSite': 'Dipteran moult disruption + nAChR ion channel block',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Imidacloprid + Thiram': {
        'code': 'IRAC 4A + FRAC M03',
        'group': 'Neonicotinoid + Dithiocarbamate Seed Dressing',
        'targetSite': 'nAChR agonist + Multi-site fungal contact inhibitor',
        'risk': 'Low',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 60,
        'rei': 24,
        'water': 0
    },
    'Tebufenozide': {
        'code': 'IRAC 18',
        'group': 'Diacylhydrazines (Ecdysone receptor agonists)',
        'targetSite': 'Ecdysone receptor agonist (premature lethal moult)',
        'risk': 'Low to Medium',
        'tox': 'U - Unlikely to Present Hazard',
        'whoColor': '#22c55e',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Fenpyroximate': {
        'code': 'IRAC 21A',
        'group': 'METI Acaricides (Mitochondrial complex I inhibitors)',
        'targetSite': 'Mitochondrial electron transport complex I',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Lufenuron + Thiamethoxam': {
        'code': 'IRAC 15 + 4A',
        'group': 'Benzoylurea + Neonicotinoid Premix',
        'targetSite': 'Chitin synthesis type 0 + nAChR competitive modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Lufenuron + Lambda Cyhalothrin': {
        'code': 'IRAC 15 + 3A',
        'group': 'Benzoylurea + Pyrethroid Premix',
        'targetSite': 'Chitin synthesis type 0 + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Dimehypo': {
        'code': 'IRAC 14',
        'group': 'Nereistoxin analogues (nAChR channel blockers)',
        'targetSite': 'Nicotinic acetylcholine receptor channel block',
        'risk': 'Medium',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Chloroisobromine Cynuruc Acid': {
        'code': 'Disinfectant',
        'group': 'Halogenated Disinfectant / Agricultural Bactericide',
        'targetSite': 'Cellular protein oxidation and bacterial membrane lysis',
        'risk': 'Low',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Flonicamid': {
        'code': 'IRAC 29',
        'group': 'Pyridine carboxamides (Chordotonal organ modulators)',
        'targetSite': 'Chordotonal organ stretch receptor modulator',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Chlorpyrifos + Fipronil': {
        'code': 'IRAC 1B + 2B',
        'group': 'Organophosphate + Phenylpyrazole Dual Action',
        'targetSite': 'AChE inhibitor + GABA chloride channel blocker',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Flubendiamide + Thiacloprid': {
        'code': 'IRAC 28 + 4A',
        'group': 'Diamide + Neonicotinoid Premix (Belt Expert)',
        'targetSite': 'Ryanodine receptor modulator + nAChR competitive modulator',
        'risk': 'Medium to High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Flupyradifurone + Flonicamid': {
        'code': 'IRAC 4D + 29',
        'group': 'Butenolide + Chordotonal Modulator Premix',
        'targetSite': 'nAChR agonist + Chordotonal organ modulator',
        'risk': 'Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Pymetrozine + Acetamiprid': {
        'code': 'IRAC 9B + 4A',
        'group': 'Chordotonal Blocker + Neonicotinoid Premix',
        'targetSite': 'TRPV feeding blocker + nAChR competitive modulator',
        'risk': 'Medium to High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 12,
        'water': 500
    },
    'Clothianidin + Lambda Cyhalothrin': {
        'code': 'IRAC 4A + 3A',
        'group': 'Neonicotinoid + Pyrethroid Premix',
        'targetSite': 'nAChR competitive modulator + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    },
    'Bifenthrin + Pyridaben + Thiodicarb': {
        'code': 'IRAC 3A + 21A + 1A',
        'group': 'Pyrethroid + METI Miticide + Carbamate Triple Action',
        'targetSite': 'Sodium channel + Complex I + AChE inhibition',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Imidacloprid + Fipronil + Deltamethrin': {
        'code': 'IRAC 4A + 2B + 3A',
        'group': 'Neonicotinoid + Phenylpyrazole + Pyrethroid Triple Action',
        'targetSite': 'nAChR agonist + GABA blocker + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 21,
        'rei': 48,
        'water': 500
    },
    'Cyantraniliprole': {
        'code': 'IRAC 28',
        'group': 'Diamides (Second generation anthranilic diamide)',
        'targetSite': 'Ryanodine receptor (RyR) modulation',
        'risk': 'Low to Medium',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Sulfoxaflor': {
        'code': 'IRAC 4C',
        'group': 'Sulfoximines (nAChR competitive modulators)',
        'targetSite': 'Nicotinic acetylcholine receptor (nAChR)',
        'risk': 'Medium to High',
        'tox': 'III - Slightly Hazardous',
        'whoColor': '#3b82f6',
        'phi': 7,
        'rei': 12,
        'water': 500
    },
    'Acetamiprid + Cypermethrin': {
        'code': 'IRAC 4A + 3A',
        'group': 'Neonicotinoid + Pyrethroid Premix',
        'targetSite': 'nAChR agonist + Sodium channel modulator',
        'risk': 'High',
        'tox': 'II - Moderately Hazardous',
        'whoColor': '#eab308',
        'phi': 14,
        'rei': 24,
        'water': 500
    }
}

print("IRAC Mapping loaded with", len(IRAC_MAP), "active ingredient definitions.")
