#!/usr/bin/env python3
"""
Regenerate src/data/all_pesticides.ts from data_raw/all_pesticides.csv
with proper newline separators in the `recommendations` field.

Background:
  The CSV contains multi-line recommendations inside quoted fields, e.g.
    "Chilli | Thrips | 100 g/ha
     Chilli | Aphid | 0.2 g/L of water
     Rice | BPH | 100 g/ha"
  But the current all_pesticides.ts collapsed these into a single line with
  no separator, e.g. "Chilli | Thrips | 100 g/haChilli | Aphid | 0.2 g/L of
  waterRice | BPH | 100 g/ha".

This script:
  - Parses the CSV with the Python csv module (which respects quoted
    multi-line fields).
  - Writes a TypeScript file that preserves newlines as the escape sequence
    "\\n" inside string literals.
  - Preserves the original type/interface definition so that downstream
    imports of `pesticides` keep working.

Usage:
  python3 /home/z/my-project/scripts/regenerate_all_pesticides.py
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path("/home/z/my-project/repos/AgriChem-Guide-Pest-Control-Database")
CSV_PATH = REPO_ROOT / "data_raw" / "all_pesticides.csv"
OUT_PATH = REPO_ROOT / "src" / "data" / "all_pesticides.ts"


def to_ts_string_literal(s: str) -> str:
    """Convert a Python str into a TS double-quoted string literal.

    - Real newlines are emitted as the two-character escape sequence ``\\n``
      so that the runtime value contains a real newline.
    - Backslashes are escaped.
    - Double quotes are escaped.
    """
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\n", "\\n")
    s = s.replace("\r", "")
    return f'"{s}"'


def to_ts_string_array(values: list[str]) -> str:
    """Format a Python list of strings as a TS array literal."""
    return "[" + ", ".join(to_ts_string_literal(v) for v in values) + "]"


def to_ts_number(value: str) -> str:
    """Parse a CSV numeric field as a number, falling back to 0."""
    value = (value or "").strip()
    if not value:
        return "0"
    try:
        # int if possible
        if value.isdigit():
            return str(int(value))
        return str(float(value))
    except ValueError:
        return "0"


HEADER_COMMENT = '''/**
 * Registered pesticides in Bangladesh — full database.
 * Source: Department of Agricultural Extension (DAE), Bangladesh —
 * List of Registered Pesticides approved up to the 81st Pesticide
 * Technical Advisory Committee (PTAC) Meeting.
 *
 * Auto-generated from CSV. Do not edit by hand.
 *
 * Last regenerated by: /home/z/my-project/scripts/regenerate_all_pesticides.py
 * Multi-line ``recommendations`` fields preserve the original CSV newline
 * separators as the escape sequence ``\\n`` inside the string literal.
 */

'''

TYPE_BLOCK = '''export type PesticideType =
  | "Insecticide"
  | "Fungicide"
  | "Herbicide"
  | "Public Health"
  | "Miticide"
  | "Store Grain Insecticide"
  | "Bio Pesticide"
  | "Rodenticide";

export interface PesticideProduct {
  /** Pesticide category (e.g. "Insecticide", "Fungicide"). */
  pesticideType: PesticideType;
  /** Common-name index (1-based) used to group brand variants within a type. */
  slNoCommonName: number;
  /** Active ingredient / technical common name. */
  commonName: string;
  /** Sequence number of the brand variant under its common name. */
  slNoProduct: number;
  /** Trade / brand name of the formulated product. */
  brandName: string;
  /** DAE registration number, e.g. "AP-890" or "PHP-769". */
  registrationNo: string;
  /** Company that holds the registration. */
  registrationHolder: string;
  /** Crops the product is recommended for. */
  recommendedCrops: string[];
  /** Pest(s) the product is recommended against. */
  recommendedPests: string[];
  /** Human-readable dosage rate summary. */
  dosageRate: string;
  /** Crop | Pest | Dosage breakdown, one per line. */
  recommendations: string;
  /** Number of separate crop-pest-dosage recommendations. */
  noOfRecommendations: number;
  /** IRAC / FRAC Mode-of-Action code, if classified. */
  moaCode: string | null;
}

'''


def main() -> int:
    if not CSV_PATH.exists():
        print(f"ERROR: CSV not found at {CSV_PATH}", file=sys.stderr)
        return 1

    with CSV_PATH.open("r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        rows = list(reader)

    expected_cols = [
        "Pesticide Type",
        "SL No (Common Name)",
        "Common Name",
        "SL No (Products)",
        "Brand Name",
        "Registration No",
        "Registration Holder",
        "Recommended Crops",
        "Recommended Pests",
        "Dosage Rate",
        "Recommendations (Crop | Pest | Dosage)",
        "No. of Recommendations",
        "MoA Code",
    ]
    if header != expected_cols:
        print(f"ERROR: CSV header mismatch", file=sys.stderr)
        print(f"Expected: {expected_cols}", file=sys.stderr)
        print(f"Got:      {header}", file=sys.stderr)
        return 2

    out_lines: list[str] = []
    out_lines.append(HEADER_COMMENT)
    out_lines.append(TYPE_BLOCK)
    out_lines.append("export const pesticides: ReadonlyArray<PesticideProduct> = [")

    multiline_count = 0
    for row in rows:
        if len(row) < 13:
            # Skip malformed rows but warn
            print(f"WARN: row has {len(row)} cols (expected 13): {row[:3]}...", file=sys.stderr)
            continue

        (
            pest_type,
            sl_no_common_name,
            common_name,
            sl_no_product,
            brand_name,
            reg_no,
            reg_holder,
            rec_crops,
            rec_pests,
            dosage_rate,
            recommendations,
            no_of_recs,
            moa_code,
        ) = row[:13]

        # Split crops / pests by comma (CSV field already de-quoted by csv module)
        crops = [c.strip() for c in rec_crops.split(",") if c.strip()]
        pests = [p.strip() for p in rec_pests.split(",") if p.strip()]

        # Trim leading/trailing newlines on recommendations but preserve interior newlines
        recommendations = recommendations.strip("\n").strip()

        if "\n" in recommendations:
            multiline_count += 1

        # moaCode may be empty -> null
        moa_code_lit = "null" if not moa_code.strip() else to_ts_string_literal(moa_code.strip())

        block = (
            "  {\n"
            f"    pesticideType: {to_ts_string_literal(pest_type)} as PesticideType,\n"
            f"    slNoCommonName: {to_ts_number(sl_no_common_name)},\n"
            f"    commonName: {to_ts_string_literal(common_name)},\n"
            f"    slNoProduct: {to_ts_number(sl_no_product)},\n"
            f"    brandName: {to_ts_string_literal(brand_name)},\n"
            f"    registrationNo: {to_ts_string_literal(reg_no)},\n"
            f"    registrationHolder: {to_ts_string_literal(reg_holder)},\n"
            f"    recommendedCrops: {to_ts_string_array(crops)},\n"
            f"    recommendedPests: {to_ts_string_array(pests)},\n"
            f"    dosageRate: {to_ts_string_literal(dosage_rate)},\n"
            f"    recommendations: {to_ts_string_literal(recommendations)},\n"
            f"    noOfRecommendations: {to_ts_number(no_of_recs)},\n"
            f"    moaCode: {moa_code_lit},\n"
            "  },"
        )
        out_lines.append(block)

    out_lines.append("];")
    out_lines.append("")  # trailing newline

    OUT_PATH.write_text("\n".join(out_lines), encoding="utf-8")

    print(f"✓ Wrote {OUT_PATH}")
    print(f"  Rows: {len(rows)}")
    print(f"  Rows with multi-line recommendations: {multiline_count}")
    print(f"  File size: {OUT_PATH.stat().st_size:,} bytes")
    print(f"  Line count: {len(out_lines):,}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
