import { ChemicalProduct } from '../types';

export const SOURCE_META = {
  sources: [
    'e55cfc1f-9697-4f5f-a037-feb6c8025e82.csv',
    'bb37d76d-e8f1-40c8-893f-48321bbe7325.csv',
    'a8cd7b76-84d0-431f-aa62-932158407ad9.csv',
    '06813019-d820-4006-bfc9-5f93525e6f5b.csv',
  ],
  meeting: '81st PTAC Meeting',
  extractionDate: '2026-09-15',
} as const;

export const SOURCE_PESTICIDES: ChemicalProduct[] = [
  // Generated by parse-csv-and-update.mjs or src/data/generateSourcePesticides.ts
  // Run: npx tsx src/data/generateSourcePesticides.ts
  // MoA codes resolved dynamically from MOA_DATABASE via moaResolver
];
